ChrootEveryone              yes
NoAnonymous                 yes
TLS                         2
PassivePortRange            30000 31000
MaxClientsNumber            80
MaxClientsPerIP             5
MaxIdleTime                 900
PureDB                      /etc/pure-ftpd/pureftpd.pdb
LimitRecursion              10000 8
VerboseLog                  yes
CertFile                    /etc/pki/tls/certs/lab-ftp.pem
