import { aliases, event } from "./state.js?v=20260802.15";

const knownCommands = ["help","hostname","hostnamectl","whoami","id","getent","pwd","cd","ls","tree","cat","less","head","tail","touch","mkdir","rmdir","cp","mv","rm","ln","find","grep","sed","awk","vi","vim","nano","date","uptime","free","top","ps","kill","df","du","mount","umount","lsblk","blkid","lsof","uname","rpm","yum","systemctl","journalctl","dmesg","firewall-cmd","getenforce","setenforce","ip","ping","telnet","traceroute","dig","nslookup","ss","netstat","curl","wget","nmcli","bridge","virsh","ssh","scp","rsync","sudo","su","reboot","shutdown","pcs","crm","corosync-cfgtool","corosync-quorumtool","drbdadm","drbdsetup","mysql","mysqldump","showmount","haproxy","varnishadm","rabbitmqctl","nodetool","pure-pw","history","exit","logout","clear"];

export function newSession(id=1) { return { id, host:"bastion01", user:"labadmin", cwd:"/home/labadmin", stack:[], history:[], historyIndex:0, mysql:false, output:[{kind:"system",text:"HA Infrastructure Lab console ready. Type help for supported commands."}] }; }
export function prompt(session) { return session.mysql ? "mysql> " : `[${session.user}@${session.host} ${session.cwd === `/home/${session.user}` || session.cwd === "/root" ? "~" : session.cwd.split("/").pop() || "/"}]${session.user === "root" ? "#" : "$"}`; }
export function completions(prefix,state,session=newSession()){
  const trailing=/\s$/.test(prefix),words=prefix.trimStart()?prefix.trimStart().split(/\s+/):[""];if(trailing)words.push("");const command=words[0],token=words.at(-1)||"";
  if(words.length===1)return knownCommands.filter(candidate=>candidate.startsWith(token));
  if(command==="ssh"){const at=token.lastIndexOf("@"),lead=at>=0?token.slice(0,at+1):"";return Object.keys(state.hosts).map(host=>lead+host).filter(candidate=>candidate.startsWith(token));}
  const host=state.hosts[session.host];
  if(["cd","ls","tree","cat","less","head","tail","touch","mkdir","rmdir","cp","mv","rm","find","grep","sed","awk","vi","vim","nano","du"].includes(command)&&host){const slash=token.lastIndexOf("/"),dirToken=slash>=0?token.slice(0,slash+1):"",nameToken=slash>=0?token.slice(slash+1):token,dirPath=resolvePath(session,dirToken||session.cwd);return virtualPaths(host).filter(path=>path!==dirPath&&parentPath(path)===dirPath&&basename(path).startsWith(nameToken)).map(path=>`${dirToken}${basename(path)}${isVirtualDirectory(host,path)?"/":""}`).sort();}
  if(command==="systemctl"){if(words.length===2)return ["status","start","stop","restart","enable","disable"].filter(action=>action.startsWith(token));if(words.length===3&&host)return Object.keys(host.services).map(service=>`${service}.service`).filter(service=>service.startsWith(token)).sort();}
  if(command==="pcs"){if(words.length===2)return ["status","resource","cluster","node","constraint","property"].filter(item=>item.startsWith(token));if(words[1]==="resource"&&words.length===3)return ["move","clear","cleanup"].filter(item=>item.startsWith(token));if(words[1]==="resource"&&words.length===4)return ["haproxy-group","database-group","storage-group"].filter(item=>item.startsWith(token));if(words[1]==="resource"&&words[2]==="move"&&words.length>=5)return Object.values(state.clusters).flatMap(cluster=>cluster.nodes).filter(node=>node.startsWith(token));if(words[1]==="cluster"&&words.length===3)return ["status","start"].filter(item=>item.startsWith(token));if(words[1]==="cluster"&&words[2]==="start"&&words.length===4)return Object.values(state.clusters).flatMap(cluster=>cluster.nodes).filter(node=>node.startsWith(token));}
  if(command==="virsh"){if(words.length===2)return ["list","dominfo","console","start","shutdown","reboot"].filter(item=>item.startsWith(token));if(words.length===3)return Object.entries(state.vms||{}).filter(([,vm])=>vm.hypervisor===session.host).map(([name])=>name).filter(name=>name.startsWith(token));}
  return [];
}
export function saveEditedFile(state,hostname,path,content,user="root") { const host=state.hosts[hostname]; if(!host)throw new Error(`Unknown virtual host: ${hostname}`); host.files[path]=content; event(state,"info",`${user} saved ${path} on ${hostname}.`); return {path,lines:content===""?0:content.split("\n").length,bytes:new TextEncoder().encode(content).length}; }

const h = (state,s) => state.hosts[s.host];
const serviceState = (host,name) => host.services[name] || "inactive (dead)";
const isActive = value => value?.startsWith("active");
const activeServiceForEngine=(state,hostname,service)=>state.hosts[hostname]?.online&&isActive(state.hosts[hostname]?.services[service]);
const canonicalService=name=>({nfs:"nfs-server",nfs_server:"nfs-server",mysql:"mariadb"}[name]||name);
const lines = (...xs) => xs.filter(x=>x!==undefined).join("\n");
const normalizeVirtualPath=path=>{const parts=[];for(const part of path.split("/")){if(!part||part===".")continue;if(part==="..")parts.pop();else parts.push(part);}return `/${parts.join("/")}`||"/";};
const resolvePath = (s,p="") => normalizeVirtualPath(p.startsWith("/")?p:`${s.cwd.replace(/\/$/,"")}/${p}`);
const basename = p => p.split("/").filter(Boolean).at(-1) || "/";
const parentPath = p => p==="/"?"/":p.slice(0,p.lastIndexOf("/"))||"/";
function virtualPaths(host){
  const paths=new Set([...(host.directories||["/"]),...Object.keys(host.files)]);
  for(const file of Object.keys(host.files)){let parent=parentPath(file);while(parent!=="/"){paths.add(parent);parent=parentPath(parent);}paths.add("/");}
  return [...paths];
}
const isVirtualDirectory=(host,path)=>(host.directories||[]).includes(path)||Object.keys(host.files).some(file=>file.startsWith(path==="/"?"/":`${path}/`));
const virtualPathExists=(host,path)=>host.files[path]!==undefined||isVirtualDirectory(host,path);
function expandVirtualTarget(host,session,target){
  if(!/[?*]/.test(target))return [target];
  const absolute=resolvePath(session,target),pattern=`^${absolute.replace(/[.+^${}()|[\]\\]/g,"\\$&").replace(/\*/g,"[^/]*").replace(/\?/g,"[^/]")}$`,matcher=new RegExp(pattern);
  return virtualPaths(host).filter(path=>matcher.test(path)).sort().map(path=>target.startsWith("/")?path:path.slice(session.cwd==="/"?1:session.cwd.length+1));
}
function virtualFileBytes(path,content){if(basename(path).startsWith("core."))return 56*1024**3;const bytes=new TextEncoder().encode(content||"").length;return Math.max(4096,Math.ceil(bytes/4096)*4096);}
function virtualUsageBytes(host,path){if(host.files[path]!==undefined&&!isVirtualDirectory(host,path))return virtualFileBytes(path,host.files[path]);const prefix=path==="/"?"/":`${path}/`;return Object.entries(host.files).filter(([file])=>file.startsWith(prefix)).reduce((sum,[file,content])=>sum+virtualFileBytes(file,content),0);}
function humanBytes(bytes){if(bytes>=1024**3)return `${Number((bytes/1024**3).toFixed(1))}G`;if(bytes>=1024**2)return `${Number((bytes/1024**2).toFixed(1))}M`;if(bytes>=1024)return `${Math.max(4,Math.ceil(bytes/1024))}K`;return `${bytes}`;}
function duCommand(host,session,args){
  const options=args.filter(arg=>arg.startsWith("-")),rawTargets=args.filter(arg=>!arg.startsWith("-")),targets=rawTargets.length?rawTargets:[session.cwd],expanded=targets.flatMap(target=>expandVirtualTarget(host,session,target)),rows=[];
  if(!expanded.length)return `du: cannot access '${targets[0]}': No such file or directory`;
  let total=0;
  for(const target of expanded){const path=resolvePath(session,target);if(!virtualPathExists(host,path)){rows.push(`du: cannot access '${target}': No such file or directory`);continue;}const bytes=virtualUsageBytes(host,path);total+=bytes;rows.push(`${humanBytes(bytes)}\t${target}`);}
  if(options.some(option=>option.includes("c"))&&rows.some(row=>!row.startsWith("du:")))rows.push(`${humanBytes(total)}\ttotal`);
  return rows.join("\n");
}
const logPathFor=(hostname,service)=>({haproxy:"/var/log/haproxy.log",mariadb:"/var/log/mariadb/mariadb.log",mysql:"/var/log/mariadb/mariadb.log",drbd:"/var/log/drbd.log",pacemaker:"/var/log/pacemaker/pacemaker.log",corosync:"/var/log/cluster/corosync.log","nfs-server":"/var/log/nfs.log",nfs_server:"/var/log/nfs.log","pure-ftpd":"/var/log/pureftpd.log",NetworkManager:"/var/log/messages","rabbitmq-server":`/var/log/rabbitmq/rabbit@${hostname}.log`,cassandra:"/var/log/cassandra/system.log",elasticsearch:"/var/log/elasticsearch/lab-search.log",libvirtd:"/var/log/libvirt/libvirtd.log"}[service]||"/var/log/messages");
function appendLog(state,hostname,path,message){const host=state.hosts[hostname];if(!host)return;host.files[path]=(host.files[path]||"")+message.replace(/\n?$/,"\n");}
function serviceLog(state,hostname,service,message,level="error"){const upper=level.toUpperCase();appendLog(state,hostname,"/var/log/messages",`Aug 02 09:18:42 ${hostname} ${service}[${service==="pacemaker"?1402:3210}]: ${upper}: ${message}`);const path=logPathFor(hostname,service);if(path!=="/var/log/messages")appendLog(state,hostname,path,`Aug 02 09:18:42 ${hostname} ${service}[3210]: ${upper}: ${message}`);}

function shellWords(raw) {
  const out=[]; let cur="", quote="";
  for(let i=0;i<raw.length;i++){ const c=raw[i]; if(quote){ if(c===quote) quote=""; else cur+=c; } else if(c==="'"||c==='"') quote=c; else if(/\s/.test(c)){ if(cur){out.push(cur);cur="";} } else cur+=c; }
  if(cur) out.push(cur); return out;
}

function clusterForHost(state,hostname){ return Object.entries(state.clusters).find(([,c])=>c.nodes.includes(hostname)); }
function failover(state,clusterName,failed){
  const c=state.clusters[clusterName]; if(!c||c.owner!==failed) return;
  const target=c.nodes.find(n=>n!==failed&&state.hosts[n].online);
  if(!target){ c.owner=null; c.quorum=false; c.nodes.forEach(n=>serviceLog(state,n,"pacemaker",`${clusterName} resource group stopped: no eligible VIP owner`,"critical"));event(state,"critical",`${clusterName} has no eligible VIP owner.`); return; }
  c.owner=target; c.quorum=true;if(c.dc===failed||!state.hosts[c.dc]?.online)c.dc=target;
  if(clusterName==="database"){ state.mysql.primary=target; c.roles="Secondary/Primary"; const svc=state.hosts[target].services; svc.mariadb="active (running)"; }
  if(clusterName==="storage"){c.roles="Secondary/Primary";state.hosts[target].services["nfs-server"]="active (running)";}
  serviceLog(state,failed,"pacemaker",`monitor operation failed for ${clusterName}; initiating recovery`,"warning");
  serviceLog(state,target,"pacemaker",`Started vip-${clusterName} ${c.vip} after migration from ${failed}`,"notice");
  event(state,"warning",`${c.vip} migrated from ${failed} to ${target}.`);
}

export function setHostPower(state,hostname,action,source="terminal"){
  const host=state.hosts[hostname];if(!host)return `Error: virtual machine '${hostname}' not found`;
  const entry=clusterForHost(state,hostname);
  const startHost=()=>{host.online=true;host.uptime="0 min";if(host.powerServices){host.services={...host.services,...host.powerServices};delete host.powerServices;}else Object.keys(host.services).forEach(service=>host.services[service]="active (running)");if(entry){const [name,cluster]=entry;cluster.quorum=cluster.nodes.some(node=>state.hosts[node].online);cluster.dc??=cluster.nodes.find(node=>state.hosts[node].online);["pacemaker","corosync","drbd"].forEach(service=>{if(service in host.services)host.services[service]="active (running)";});if(name==="database")host.services.mariadb=cluster.owner===hostname?"active (running)":"inactive (dead)";if(name==="storage")host.services["nfs-server"]=cluster.owner===hostname?"active (running)":"inactive (dead)";}serviceLog(state,hostname,"systemd","virtual machine boot completed; services restored","notice");};
  if(action==="start"){if(host.online)return `Domain ${hostname} is already running`;startHost();if(source==="management")host.history.push(`powerctl start ${hostname}`);event(state,"info",`${hostname} ${source==="management"?"node powered on through out-of-band management":"virtual machine started"}.`);return `Domain ${hostname} started`;}
  if(action!=="shutdown"&&action!=="reboot")return `Error: unsupported power action '${action}'`;
  if(!host.online)return `Domain ${hostname} is not running`;
  host.powerServices={...host.services};host.online=false;host.uptime="0 min";Object.keys(host.services).forEach(service=>host.services[service]="inactive (dead)");if(entry){failover(state,entry[0],hostname);if(entry[1].dc===hostname)entry[1].dc=entry[1].nodes.find(node=>state.hosts[node].online)||null;}
  if(action==="shutdown"){event(state,"warning",`${hostname} virtual machine shut down.`);return `Domain ${hostname} is being shutdown`;}
  startHost();event(state,"info",`${hostname} virtual machine reboot completed.`);return `Domain ${hostname} rebooted`;
}

function help(){ return `Allowlisted simulated commands\n\nSystem: hostname hostnamectl whoami id pwd cd ls tree cat tail touch mkdir rmdir cp mv rm find grep date uptime free top ps df du mount lsblk uname rpm yum\nServices: systemctl journalctl dmesg firewall-cmd ip ping telnet dig ss nmcli bridge virsh\nAccess: ssh scp rsync sudo su exit logout\nHA: pcs crm corosync-cfgtool corosync-quorumtool drbdadm drbdsetup\nPlatforms: mysql mysqldump haproxy varnishadm rabbitmqctl nodetool curl showmount\n\nCommands change only browser-stored fictional lab state. Try: ssh root@mysql-core01` }

function listFiles(host,session,args){
  const target=args.find(a=>!a.startsWith("-"))||session.cwd, p=resolvePath(session,target);
  if(host.files[p]!==undefined&&!isVirtualDirectory(host,p)) return basename(p);
  if(!isVirtualDirectory(host,p))return `ls: cannot access '${target}': No such file or directory`;
  const entries=virtualPaths(host).filter(path=>path!==p&&parentPath(path)===p).map(path=>basename(path));
  if(args.some(a=>a.includes("a")))entries.unshift(".","..");
  if(args.some(a=>a.includes("l"))) return entries.map(x=>{if(x==="."||x==="..")return `drwxr-xr-x. 2 root root 4096 Aug  1 10:12 ${x}`;const path=p==="/"?`/${x}`:`${p}/${x}`,directory=isVirtualDirectory(host,path),size=directory?4096:virtualFileBytes(path,host.files[path]);return `${directory?"drwxr-xr-x":"-rw-r--r--"}. 1 root root ${size} Aug  1 10:12 ${x}`;}).join("\n");
  return entries.join("  ");
}

function treeFiles(host,session,args){const target=args.find(arg=>!arg.startsWith("-"))||session.cwd,path=resolvePath(session,target);if(!virtualPathExists(host,path))return `tree: ${target}: No such file or directory`;if(!isVirtualDirectory(host,path))return basename(path);const descendants=virtualPaths(host).filter(candidate=>candidate!==path&&candidate.startsWith(path==="/"?"/":`${path}/`)).sort(),rows=[target];let directories=0,files=0;for(const candidate of descendants){const relative=candidate.slice(path==="/"?1:path.length+1),depth=relative.split("/").length-1,directory=isVirtualDirectory(host,candidate);directory?directories++:files++;rows.push(`${"    ".repeat(depth)}└── ${basename(candidate)}${directory?"/":""}`);}rows.push("",`${directories} directories, ${files} files`);return rows.join("\n");}

function filesCommand(state,s,cmd,args,raw){ const host=h(state,s);
  if(cmd==="pwd") return s.cwd;
  if(cmd==="cd"){ const target=args[0]||`/home/${s.user}`,p=resolvePath(s,target);if(host.files[p]!==undefined&&!isVirtualDirectory(host,p))return `-bash: cd: ${target}: Not a directory`;if(!isVirtualDirectory(host,p))return `-bash: cd: ${target}: No such file or directory`;s.cwd=p; return ""; }
  if(cmd==="ls")return listFiles(host,s,args);if(cmd==="tree")return treeFiles(host,s,args);
  if(["cat","less","head","tail"].includes(cmd)){
    const path=resolvePath(s,args.filter(a=>!a.startsWith("-")&&a!=="f").at(-1)||""); let value=host.files[path];
    if(path==="/proc/drbd") value=drbdOutput(state,s);
    if(value===undefined) return `${cmd}: ${path}: No such file or directory`;
    const arr=value.split("\n"); if(cmd==="head") return arr.slice(0,10).join("\n"); if(cmd==="tail") return arr.slice(-10).join("\n")+(args.includes("-f")?"\n-- follow mode simulated; press Ctrl+C to return --":""); return value;
  }
  if(cmd==="touch"){const errors=[];for(const target of args.filter(a=>!a.startsWith("-"))){const p=resolvePath(s,target),parent=parentPath(p);if(!isVirtualDirectory(host,parent)){errors.push(`touch: cannot touch '${target}': No such file or directory`);continue;}if(!isVirtualDirectory(host,p))host.files[p]??="";}return errors.join("\n");}
  if(cmd==="mkdir"){const recursive=args.some(a=>a==="-p"||a==="--parents"),errors=[];for(const target of args.filter(a=>!a.startsWith("-"))){const p=resolvePath(s,target);if(virtualPathExists(host,p)){if(!recursive)errors.push(`mkdir: cannot create directory '${target}': File exists`);continue;}const parent=parentPath(p);if(!isVirtualDirectory(host,parent)&&!recursive){errors.push(`mkdir: cannot create directory '${target}': No such file or directory`);continue;}if(recursive){let cursor=p,chain=[];while(cursor!=="/"&&!isVirtualDirectory(host,cursor)){chain.unshift(cursor);cursor=parentPath(cursor);}host.directories.push(...chain);}else host.directories.push(p);host.directories=[...new Set(host.directories)].sort();event(state,"info",`${s.user} created directory ${p} on ${s.host}.`);}return errors.join("\n");}
  if(cmd==="rmdir"){const errors=[];for(const target of args.filter(a=>!a.startsWith("-"))){const p=resolvePath(s,target);if(!isVirtualDirectory(host,p)){errors.push(`rmdir: failed to remove '${target}': No such file or directory`);continue;}const hasChildren=virtualPaths(host).some(path=>path!==p&&parentPath(path)===p);if(hasChildren){errors.push(`rmdir: failed to remove '${target}': Directory not empty`);continue;}host.directories=host.directories.filter(path=>path!==p);}return errors.join("\n");}
  if(cmd==="cp"||cmd==="mv"){const cleanArgs=args.filter(a=>!a.startsWith("-")),sourceArg=cleanArgs.at(-2),destArg=cleanArgs.at(-1),src=resolvePath(s,sourceArg),destination=resolvePath(s,destArg),dst=isVirtualDirectory(host,destination)?`${destination.replace(/\/$/,"")}/${basename(src)}`:destination;if(!virtualPathExists(host,src))return `${cmd}: cannot stat '${sourceArg}': No such file or directory`;if(isVirtualDirectory(host,src))return `${cmd}: -r not specified; omitting directory '${sourceArg}'`;if(!isVirtualDirectory(host,parentPath(dst)))return `${cmd}: cannot create regular file '${destArg}': No such file or directory`;host.files[dst]=host.files[src];if(cmd==="mv")delete host.files[src];return ""; }
  if(cmd==="ln"){const target=resolvePath(s,args.at(-2)),link=resolvePath(s,args.at(-1));host.files[link]=`[symbolic link -> ${target}]`;return "";}
  if(cmd==="rm"){
    const recursive=args.some(a=>/^-[^-]*[rR]/.test(a)||a==="--recursive"),force=args.some(a=>/^-[^-]*f/.test(a)||a==="--force"),rawTargets=args.filter(a=>!a.startsWith("-")),errors=[];let removed=0,removedCore=false;
    for(const rawTarget of rawTargets){const expanded=expandVirtualTarget(host,s,rawTarget),targets=expanded.length?expanded:[rawTarget];for(const target of targets){const p=resolvePath(s,target),directory=isVirtualDirectory(host,p);if(directory&&!recursive){errors.push(`rm: cannot remove '${target}': Is a directory`);continue;}if(directory){const prefix=p==="/"?"/":`${p}/`;for(const file of Object.keys(host.files).filter(file=>file.startsWith(prefix))){removedCore||=basename(file).startsWith("core.");delete host.files[file];removed++;}continue;}if(host.files[p]!==undefined){removedCore||=basename(p).startsWith("core.");delete host.files[p];removed++;}else if(!force)errors.push(`rm: cannot remove '${target}': No such file or directory`);}}
    if(recursive)host.directories=host.directories.filter(directory=>!rawTargets.some(target=>{const path=resolvePath(s,target);return directory===path||directory.startsWith(`${path}/`);}));
    if(removedCore&&/^(dr-)?san\d{2}$/.test(s.host)){ host.disk=Math.max(42,host.disk-50); event(state,"info",`Removed simulated core files on ${s.host}; disk use is now ${host.disk}%.`); }
    return errors.join("\n");
  }
  if(cmd==="find"){ const base=resolvePath(s,args[0]||s.cwd),pattern=args[args.indexOf("-name")+1];if(!virtualPathExists(host,base))return `find: '${args[0]||s.cwd}': No such file or directory`;const matches=virtualPaths(host).filter(f=>f.startsWith(base)&&(!pattern||pattern==="core.*"&&basename(f).startsWith("core."))); return matches.join("\n"); }
  if(cmd==="grep"){ const pattern=args.find(a=>!a.startsWith("-")),path=resolvePath(s,args.at(-1)),insensitive=args.some(a=>a.includes("i")),needle=insensitive?pattern?.toLowerCase():pattern; return (host.files[path]||"").split("\n").filter(l=>(insensitive?l.toLowerCase():l).includes(needle)).join("\n"); }
  if(cmd==="sed"){
    const path=resolvePath(s,args.at(-1));if(host.files[path]===undefined)return `sed: can't read ${path}: No such file or directory`;
    const expr=args.find(a=>a.includes("/d")||a.startsWith("s/"))||"";
    if(expr.includes("/d")){const needle=expr.replace(/^\//,"").replace(/\/d.*$/,"");host.files[path]=host.files[path].split("\n").filter(l=>!l.includes(needle)).join("\n");}
    else if(expr.startsWith("s/")){const bits=expr.split("/");host.files[path]=host.files[path].split(bits[1]).join(bits[2]);}
    return args.includes("-i")?"":host.files[path];
  }
  if(cmd==="awk"){const path=resolvePath(s,args.at(-1));return (host.files[path]||"").split("\n").map(l=>l.split(/\s+/)[0]).join("\n");}
  if(["vi","vim","nano"].includes(cmd)){const path=resolvePath(s,args.at(-1)||"");return {editor:{command:cmd,path,content:host.files[path]??"",hostname:s.host,user:s.user,isNew:host.files[path]===undefined}};}
  return null;
}

function serviceCommand(state,s,args){ const host=h(state,s),action=args[0]||"status",name=canonicalService((args[1]||"").replace(".service","")); if(!name)return "systemctl: missing service name";
  if(!(name in host.services))return `Unit ${name}.service could not be found.`;
  if(action==="status") { const st=serviceState(host,name); return `● ${name}.service - ${name} service\n   Loaded: loaded (/usr/lib/systemd/system/${name}.service; enabled)\n   Active: ${st} since Sat 2026-08-01 10:12:03 IST\n Main PID: ${isActive(st)?2210:"-"} (${name})\n   CGroup: /system.slice/${name}.service`; }
  if(["start","restart"].includes(action)){
    if(name==="haproxy" && (host.files["/etc/haproxy/haproxy.cfg"]||"").includes("INVALID")){serviceLog(state,s.host,"haproxy","configuration validation failed; service not started","alert");return `Job for haproxy.service failed. Run 'haproxy -c -f /etc/haproxy/haproxy.cfg' for details.`;}
    if(name==="haproxy"&&host.files["/run/haproxy.pid"]!==undefined){host.services[name]="failed";serviceLog(state,s.host,"haproxy","startup aborted: pidfile /run/haproxy.pid exists but process 2188 is not running","alert");return "Job for haproxy.service failed because the control process exited with error code.\nSee 'journalctl -u haproxy' for details.";}
    if(name==="rabbitmq-server"&&host.files["/var/lib/rabbitmq/.erlang.cookie"]!==host.files["/etc/rabbitmq/lab.erlang.cookie"]){host.services[name]="failed";serviceLog(state,s.host,name,"BOOT FAILED: invalid challenge reply; Erlang cookie does not match cluster cookie","error");return "Job for rabbitmq-server.service failed: BOOT FAILED (invalid challenge reply).";}
    if(name==="cassandra"){const config=host.files["/etc/cassandra/cassandra.yaml"]||"";if(!config.includes(`listen_address: ${host.ip}`)){host.services[name]="failed";serviceLog(state,s.host,name,`ConfigurationException: listen_address resolves to an invalid local address; expected ${host.ip}`,"error");return "Job for cassandra.service failed: ConfigurationException in /etc/cassandra/cassandra.yaml.";}}
    if(name==="pure-ftpd"){const validCert=host.files["/etc/pki/tls/certs/lab-ftp.pem"]===host.files["/etc/pki/tls/certs/lab-ftp-renewed.pem"];if(!validCert){state.ftp.tlsValid=false;host.services[name]="failed";serviceLog(state,s.host,name,"TLS context initialization failed: certificate has expired","error");return "Job for pure-ftpd.service failed: TLS certificate has expired.";}if(!state.ftp.passiveOpen){host.services[name]="failed";serviceLog(state,s.host,name,"passive port range 30000-31000 is blocked by firewalld","error");return "Job for pure-ftpd.service failed: passive port range is unavailable.";}state.ftp.tlsValid=true;}
    host.services[name]="active (running)";
    if(name==="rabbitmq-server"&&s.host.includes("rabbitmq")){host.online=true;state.rabbitOnline=[1,2,3].filter(n=>activeServiceForEngine(state,`rabbitmq0${n}`,"rabbitmq-server")).length;}
    if(name==="cassandra"&&s.host.includes("cassandra")){host.online=true;state.cassandraOnline=[1,2,3].filter(n=>activeServiceForEngine(state,`cassandra0${n}`,"cassandra")).length;}
    if(name==="elasticsearch"&&s.host.includes("elasticsearch")){host.online=true;state.elastic=state.elasticAllocation==="none"?"red":[1,2,3].every(n=>activeServiceForEngine(state,`elasticsearch0${n}`,"elasticsearch"))?"green":"yellow";}
    serviceLog(state,s.host,name,`${action==="restart"?"Restarted":"Started"} ${name}.service successfully`,"notice"); event(state,"info",`${name} ${action}ed on ${s.host}.`); return "";
  }
  if(action==="stop") { host.services[name]="inactive (dead)";serviceLog(state,s.host,name,`${name}.service entered inactive state by operator request`,"warning"); event(state,"warning",`${name} stopped on ${s.host}.`); if(name==="mariadb"&&state.clusters.database.owner===s.host)failover(state,"database",s.host); if(name==="nfs-server"&&state.clusters.storage.owner===s.host)failover(state,"storage",s.host); if(name==="haproxy"&&state.clusters.haproxy.owner===s.host)failover(state,"haproxy",s.host); return ""; }
  if(action==="enable"||action==="disable") return `Created symlink /etc/systemd/system/multi-user.target.wants/${name}.service → /usr/lib/systemd/system/${name}.service.`;
  return `Unknown operation ${action}.`;
}

function pcsStatus(state,s){const local=clusterForHost(state,s?.host),clusters=local?[local]:Object.entries(state.clusters);return clusters.map(([name,c])=>`Cluster name: lab-${name}\nStack: corosync\nCurrent DC: ${c.dc||"NONE"}\nQuorum: ${c.quorum?"Yes":"No"}\n\nOnline: [ ${c.nodes.filter(n=>state.hosts[n].online).join(" ")} ]\n${c.nodes.filter(n=>!state.hosts[n].online).length?`OFFLINE: [ ${c.nodes.filter(n=>!state.hosts[n].online).join(" ")} ]\n`:""}\nFull List of Resources:\n  Resource Group: ${name}-group\n    vip-${name}\t(ocf::heartbeat:IPaddr2):\tStarted ${c.owner||"Stopped"}${c.drbd?`\n    drbd-${name}\t(ocf::linbit:drbd):\t${c.drbd} ${c.roles}`:""}${c.failures?`\n\nFailed Resource Actions:\n  ${name}-group monitor on ${c.lastFailedNode||c.nodes[0]} returned 'not running' (${c.failures} failure)`:""}`).join("\n\n"); }
function normalizePcsArgs(args){const normalized=[];for(let i=0;i<args.length;i++){if(args[i]==="-f"||args[i]==="--file"){i++;continue;}if(args[i].startsWith("--file="))continue;normalized.push(args[i]);}return normalized;}
function clusterResourceEntry(state,resource){const aliasesByCluster={haproxy:["haproxy","haproxy-group","vip-haproxy","lb-vip","10.10.10.10"],database:["database","database-group","vip-database","db-vip","mysql-vip","10.10.20.10"],storage:["storage","storage-group","vip-storage","san-vip","nfs-vip","10.10.30.10"]};return Object.entries(state.clusters).find(([name,c])=>aliasesByCluster[name].includes(resource)||c.vip===resource);}
function moveClusterResource(state,s,resource,target){const entry=clusterResourceEntry(state,resource);if(!entry)return `Error: resource '${resource}' not found`;const [name,cluster]=entry;if(!target)return "Error: destination node is required\nUsage: pcs resource move <resource> <node>";if(!cluster.nodes.includes(target))return `Error: node '${target}' is not a valid member for ${resource}`;if(!state.hosts[target]?.online)return `Error: node '${target}' is offline; cannot move ${resource}`;const previous=cluster.owner;cluster.owner=target;cluster.quorum=true;cluster.moveConstraint={resource,target,createdBy:s.user};if(cluster.drbd)cluster.roles=cluster.nodes.indexOf(target)===0?"Primary/Secondary":"Secondary/Primary";if(name==="database"){state.mysql.primary=target;cluster.nodes.forEach(node=>state.hosts[node].services.mariadb=node===target?"active (running)":"inactive (dead)");serviceLog(state,target,"mariadb","promoted to active write-service role after operator resource move","notice");}if(name==="storage")cluster.nodes.forEach(node=>state.hosts[node].services["nfs-server"]=node===target?"active (running)":"inactive (dead)");serviceLog(state,previous,"pacemaker",`${resource} migration requested from ${previous} to ${target}`,"notice");serviceLog(state,target,"pacemaker",`${resource} and VIP ${cluster.vip} started on ${target}`,"notice");event(state,"info",`${resource} moved from ${previous} to ${target}; VIP ${cluster.vip} now owned by ${target}.`);return previous===target?`Resource '${resource}' is already running on '${target}'. Location constraint refreshed.`:`Location constraint created for '${resource}' on '${target}'.\nResource successfully moved from ${previous} to ${target}.`;}
function pcsCommand(state,s,rawArgs){const args=normalizePcsArgs(rawArgs),sub=args[0]||"status";if(sub==="status")return pcsStatus(state,s);if(sub==="cluster"){
  const action=args[1]||"status";if(action==="status")return pcsStatus(state,s);
  if(action==="start"){const target=args[2]||s.host,host=state.hosts[target],entry=clusterForHost(state,target);if(!host)return `Error: node '${target}' not found`;if(!entry)return `Error: node '${target}' is not a cluster member`;host.online=true;host.uptime="0 min";["pacemaker","corosync","drbd"].forEach(service=>host.services[service]="active (running)");if(entry[0]==="storage")host.services["nfs-server"]=entry[1].owner===target?"active (running)":"inactive (dead)";if(entry[0]==="database")host.services.mariadb=entry[1].owner===target?"active (running)":"inactive (dead)";entry[1].quorum=entry[1].nodes.filter(node=>state.hosts[node].online).length>=Math.ceil(entry[1].nodes.length/2);entry[1].drbd&&(entry[1].drbd="Connected");serviceLog(state,target,"pacemaker",`${target} rejoined ${entry[0]} cluster; resource probes completed successfully`,"notice");event(state,"info",`${target} rejoined the ${entry[0]} cluster.`);return `${target}: Starting Cluster...\nCorosync started\nPacemaker started\n${target} successfully rejoined cluster '${entry[0]}'.`;}
  return `Error: unsupported pcs cluster action '${action}'`;
}if(sub==="resource"){
  const action=args[1];if(action==="cleanup"){const resource=args[2],entries=resource?[clusterResourceEntry(state,resource)].filter(Boolean):Object.entries(state.clusters);if(resource&&!entries.length)return `Error: resource '${resource}' not found`;entries.forEach(([,cluster])=>{cluster.failures=0;delete cluster.lastFailedNode;});event(state,"info",`Resource failures cleaned up by ${s.user}.`);return resource?`Cleaned up ${resource} on all nodes.`:"Cleaned up all resources.";}
  if(action==="move"){const resource=args[2],nodeAt=args.indexOf("--node"),nodeEquals=args.find(a=>a.startsWith("--node=")),target=nodeAt>=0?args[nodeAt+1]:nodeEquals?.split("=")[1]||args[3];return moveClusterResource(state,s,resource,target);}
  if(action==="clear"||action==="unmove"){const entry=clusterResourceEntry(state,args[2]);if(!entry)return `Error: resource '${args[2]}' not found`;delete entry[1].moveConstraint;event(state,"info",`Temporary move constraint cleared for ${args[2]}.`);return `Removing constraint created by pcs resource move ${args[2]}`;}
  return pcsStatus(state,s);
}if(sub==="node")return Object.values(state.clusters).flatMap(c=>c.nodes).map(n=>`${n}: ${state.hosts[n].online?"Online":"Offline"}`).join("\n");if(sub==="property")return "stonith-enabled: true\nno-quorum-policy: stop\nresource-stickiness: 100";if(sub==="constraint"){const moves=Object.entries(state.clusters).filter(([,c])=>c.moveConstraint).map(([name,c])=>`  ${c.moveConstraint.resource} prefers ${c.moveConstraint.target}=INFINITY`).join("\n");return `Location Constraints:\n${moves||"  No temporary location constraints"}\nOrdering Constraints:\n  promote drbd then start vip\nColocation Constraints:\n  vip with drbd-master INFINITY`;}return pcsStatus(state,s);}
function drbdOutput(state,s){ const entry=clusterForHost(state,s.host),c=entry?.[1]||state.clusters.database; return `r0 role:${c.roles?.split("/")[c.nodes.indexOf(s.host)]||"Secondary"}\n  disk:UpToDate\n  peer role:${c.roles?.split("/")[1-c.nodes.indexOf(s.host)]||"Primary"}\n    replication:${c.drbd||"Connected"} peer-disk:UpToDate done:100.00`; }

function mysqlShell(state,s,raw){ const q=raw.trim().replace(/;$/,"").toUpperCase(); if(q==="EXIT"||q==="QUIT"||q==="\\Q"){s.mysql=false;return "Bye";} if(q==="SHOW DATABASES")return "+--------------------+\n| Database           |\n+--------------------+\n| information_schema |\n| app_database       |\n| monitoring         |\n+--------------------+\n3 rows in set (0.00 sec)"; if(q==="SHOW PROCESSLIST")return "+----+----------+-----------+------+---------+------+------------------------+\n| Id | User     | Host      | db   | Command | Time | State                  |\n+----+----------+-----------+------+---------+------+------------------------+\n| 42 | repl_lab | 10.10.0.0| NULL | Binlog  |  112 | Master has sent event  |\n| 51 | labadmin | localhost | NULL | Query   |    0 | starting               |\n+----+----------+-----------+------+---------+------+------------------------+"; if(q==="SHOW MASTER STATUS")return `+------------------+----------+--------------+------------------+-------------------+\n| File             | Position | Binlog_Do_DB | Binlog_Ignore_DB | Executed_Gtid_Set |\n+------------------+----------+--------------+------------------+-------------------+\n| ${state.mysql.log} | ${state.mysql.position}   |              |                  | ${state.mysql.gtid} |\n+------------------+----------+--------------+------------------+-------------------+`; if(q.includes("SHOW SLAVE STATUS")||q.includes("SHOW REPLICA STATUS"))return `*************************** 1. row ***************************\n             Replica_IO_State: ${state.mysql.io?"Waiting for source to send event":"Connecting to source"}\n                  Source_Host: ${state.mysql.primary}\n                Source_Log_File: ${state.mysql.log}\n          Read_Source_Log_Pos: ${state.mysql.position}\n             Replica_IO_Running: ${state.mysql.io?"Yes":"No"}\n            Replica_SQL_Running: ${state.mysql.sql?"Yes":"No"}\n          Seconds_Behind_Source: ${state.mysql.io&&state.mysql.sql?state.mysql.lag:"NULL"}\n                 Channel_Name: ${state.mysql.channel}\n                    Last_Error: ${state.mysql.error}`; if(q.startsWith("STOP SLAVE")||q.startsWith("STOP REPLICA")){state.mysql.io=false;state.mysql.sql=false;event(state,"warning",`MySQL replication ${state.mysql.channel} stopped.`);return "Query OK, 0 rows affected (0.01 sec)";} if(q.startsWith("START SLAVE")||q.startsWith("START REPLICA")){state.mysql.io=true;state.mysql.sql=true;state.mysql.error="";state.mysql.lag=0;event(state,"info",`MySQL replication ${state.mysql.channel} recovered.`);return "Query OK, 0 rows affected (0.02 sec)";} if(q.includes("@@HOSTNAME"))return `+----------------+\n| @@hostname     |\n+----------------+\n| ${s.host.padEnd(14)} |\n+----------------+`; return `ERROR 1064 (42000): You have an error in your SQL syntax near '${raw.slice(0,40)}'`; }

function guardedMysqlShell(state,s,raw){const q=raw.trim().replace(/;$/,"").toUpperCase();if(q.startsWith("SET GLOBAL SQL_SLAVE_SKIP_COUNTER")||q.startsWith("SET GLOBAL SQL_REPLICA_SKIP_COUNTER")){state.mysql.skipCounterReady=true;serviceLog(state,s.host,"mariadb","operator set sql_slave_skip_counter=1 after validating duplicate-key conflict","warning");return "Query OK, 0 rows affected (0.01 sec)";}if((q.startsWith("START SLAVE")||q.startsWith("START REPLICA"))&&state.mysql.error&&!state.mysql.skipCounterReady){state.mysql.io=true;state.mysql.sql=false;serviceLog(state,s.host,"mariadb","Replica SQL thread cannot start: unresolved Error 1062; data reconciliation required","error");return "ERROR 1872 (HY000): Replica failed to initialize relay log recovery; inspect Last_Error.";}const output=mysqlShell(state,s,raw);if(q.startsWith("START SLAVE")||q.startsWith("START REPLICA"))state.mysql.skipCounterReady=false;return output;}

function platformCommand(state,s,cmd,args,raw){ const host=h(state,s);
  if(cmd==="haproxy") { const cfg=host.files["/etc/haproxy/haproxy.cfg"]||"";if(cfg.includes("INVALID")){serviceLog(state,s.host,"haproxy","configuration check failed at /etc/haproxy/haproxy.cfg: unknown keyword 'INVALID'","alert");return "[ALERT] parsing [/etc/haproxy/haproxy.cfg:8] : unknown keyword 'INVALID'.\n[ALERT] Fatal errors found in configuration.";}appendLog(state,s.host,"/var/log/haproxy.log",`Aug 02 09:19:01 ${s.host} haproxy[check]: NOTICE: configuration file validation succeeded`);return "Configuration file is valid"; }
  if(cmd==="varnishadm")return "Status: running\nChild in state running";
  if(cmd==="rabbitmqctl")return args[0]==="list_queues"?"name\tmessages\nlab.events\t0\nlab.jobs\t12":`Cluster status of node rabbit@${s.host} ...\nDisk Nodes: [rabbit@rabbitmq01,rabbit@rabbitmq02,rabbit@rabbitmq03]\nRunning Nodes: ${state.rabbitOnline}\nPartitions: []`;
  if(cmd==="nodetool")return args[0]==="repair"?"Repair completed successfully":`Datacenter: ${host.dc}\nStatus=Up/Down | State=Normal\nUN  ${host.ip}  82.4 GB  256 tokens  rack1`;
  if(cmd==="curl"){if(raw.includes("9200/_cluster/settings")&&/allocation[._]enable|allocation[^a-z]+enable/i.test(raw)&&/all/i.test(raw)){state.elasticAllocation="all";state.elastic="green";serviceLog(state,"elasticsearch02","elasticsearch","cluster.routing.allocation.enable set to all; unassigned primary shards allocated","notice");event(state,"info","Elasticsearch shard allocation restored; cluster is GREEN.");return '{"acknowledged":true,"persistent":{"cluster.routing.allocation.enable":"all"}}';}if(raw.includes("9200/_cluster/settings"))return JSON.stringify({persistent:{"cluster.routing.allocation.enable":state.elasticAllocation}},null,2);if(raw.includes("9200/_cluster/allocation/explain"))return JSON.stringify({index:"app-events-2026.08.02",shard:2,primary:true,current_state:"unassigned",unassigned_info:{reason:"ALLOCATION_FAILED"},allocate_explanation:state.elasticAllocation==="none"?"cannot allocate because cluster.routing.allocation.enable is [none]":"allocation is permitted"},null,2);if(raw.includes("9200/_cluster/health"))return JSON.stringify({cluster_name:"lab-search",status:state.elastic,number_of_nodes:6,active_primary_shards:state.elastic==="green"?24:21,unassigned_shards:state.elastic==="green"?0:3},null,2); if(raw.includes("9200/_cat/nodes"))return "ip heap.percent ram.percent cpu load_1m node.role master name\n10.10.62.21 24 62 3 0.12 cdfhilmrstw * elasticsearch01\n10.10.62.22 19 58 2 0.08 cdfhilmrstw - elasticsearch02"; return "HTTP/1.1 200 OK\nX-Lab-Simulation: true\n\nhealthy";}
  if(cmd==="showmount")return "Export list for san-vip:\n/exports/app 10.10.0.0/16\n/exports/backups 10.10.0.0/16";
  return null;
}

function networking(state,s,cmd,args,raw){ const host=h(state,s);
  if(cmd==="ip"){if(args[0]==="a"||args[0]==="addr") { const vip=Object.values(state.clusters).find(c=>c.owner===s.host)?.vip; return host.interfaces.map((x,i)=>`${i+1}: ${x.name}: <BROADCAST,MULTICAST,${x.state}> mtu 1500 state ${x.state}\n    inet ${x.ip} scope global ${x.name}`).join("\n")+(vip?`\n    inet ${vip}/24 scope global secondary ens192` :"");} if(args[0]==="route")return host.routes.join("\n"); if(args[0]==="link")return host.interfaces.map((x,i)=>`${i+1}: ${x.name}: <${x.state}> state ${x.state}`).join("\n");}
  if(cmd==="dig"||cmd==="nslookup"){const name=args.find(a=>!a.startsWith("+"))||"app.lab.internal",dnsOk=host.files["/etc/resolv.conf"]?.includes(host.dc==="recovery"?"10.20.50.11":"10.10.50.11");return dnsOk?`; <<>> DiG 9.11 <<>> ${name}\n;; status: NOERROR\n${name}. 300 IN A ${name.startsWith("dns01")?"10.10.50.11":state.clusters.database.vip}`:`;; communications error to 127.0.0.1#53: connection refused\n;; no servers could be reached`;}
  if(cmd==="ping"){const target=args.at(-1),dest=state.hosts[aliases[target]||target]; if(dest&&!dest.online)return `From ${host.ip} icmp_seq=1 Destination Host Unreachable`;return `PING ${target} (${dest?.ip||"10.10.10.10"}) 56(84) bytes of data.\n64 bytes from ${dest?.ip||"10.10.10.10"}: icmp_seq=1 ttl=64 time=0.421 ms\n\n--- ${target} ping statistics ---\n1 packets transmitted, 1 received, 0% packet loss`;}
  if(cmd==="telnet"){if(!host.packages.some(pkg=>pkg.startsWith("telnet-")))return "-bash: telnet: command not found";const target=args[0],port=Number(args[1]||23),dest=state.hosts[aliases[target]||target]||Object.values(state.hosts).find(candidate=>candidate.ip===target);if(!dest)return `telnet: ${target}: Name or service not known`;if(!dest.online)return `Trying ${dest.ip}...\ntelnet: connect to address ${dest.ip}: No route to host`;const open=port===22||(port===7789&&dest.hostname.includes("mysql-core")&&!state.clusters.database.drbdPortBlocked&&isActive(dest.services.drbd))||(port===3306&&isActive(dest.services.mariadb))||(port===21&&isActive(dest.services["pure-ftpd"])&&state.ftp.tlsValid&&state.ftp.passiveOpen)||(port===80&&(isActive(dest.services.haproxy)||isActive(dest.services.nginx)));return open?`Trying ${dest.ip}...\nConnected to ${dest.ip}.\nEscape character is '^]'.\nConnection closed by foreign host.`:`Trying ${dest.ip}...\ntelnet: connect to address ${dest.ip}: Connection refused`;}
  if(cmd==="ss"||cmd==="netstat")return `State  Recv-Q Send-Q Local Address:Port Peer Address:Port Process\nLISTEN 0      128    0.0.0.0:22       0.0.0.0:*     users:(("sshd",pid=944,fd=3))\n${isActive(host.services.mariadb)?'LISTEN 0      80     0.0.0.0:3306     0.0.0.0:*     users:(("mysqld",pid=2210,fd=21))':""}${isActive(host.services["pure-ftpd"])?'\nLISTEN 0      128    0.0.0.0:21       0.0.0.0:*     users:(("pure-ftpd",pid=2031,fd=4))':""}`;
  if(cmd==="traceroute")return `traceroute to ${args[0]}, 30 hops max\n 1  10.10.0.1  0.281 ms\n 2  ${args[0]}  0.557 ms`;
  if(cmd==="firewall-cmd"){if(args.includes("sudo")||args.slice(1).includes("firewall-cmd"))return "usage: firewall-cmd [OPTIONS...]\nfirewall-cmd: error: unrecognized arguments: sudo firewall-cmd --reload";state.firewall[s.host]??={ports:[],pending:[]};const fw=state.firewall[s.host];if(raw.includes("--list-all"))return `public (active)\n  interfaces: ens192\n  services: ssh cockpit\n  ports: ${["80/tcp","443/tcp",...fw.ports].join(" ")}`;if(raw.includes("--list-ports"))return fw.ports.join(" ");const query=raw.match(/--query-port(?:=|\s+)([^\s]+)/);if(query)return (raw.includes("--permanent")?fw.pending.includes(query[1])||fw.ports.includes(query[1]):fw.ports.includes(query[1]))?"yes":"no";const add=raw.match(/--add-port(?:=|\s+)([^\s]+)/);if(add){if(raw.includes("--permanent")){if(!fw.pending.includes(add[1]))fw.pending.push(add[1]);return "success";}if(!fw.ports.includes(add[1]))fw.ports.push(add[1]);return "success";}if(raw.includes("--reload")){fw.ports=[...new Set([...fw.ports,...fw.pending])];fw.pending=[];if(fw.ports.includes("7789/tcp")&&state.clusters.database.drbdPortBlocked)state.clusters.database.drbdPortBlocked=false;if(fw.ports.includes("30000-31000/tcp"))state.ftp.passiveOpen=true;return "success";}return "success";}
  return null;
}

function nmcliCommand(state,s,args){const host=h(state,s),connections=host.connections;
  if(["con","conn","connection"].includes(args[0])){
    if(args.includes("show"))return `NAME           UUID                                  TYPE      DEVICE\n${Object.entries(connections).map(([name,x],i)=>`${name.padEnd(14)} 00000000-0000-0000-0000-${String(i+1).padStart(12,"0")}  ${x.type.padEnd(9)} ${x.state==="up"?x.device:"--"}`).join("\n")}`;
    const action=args[1];
    if(action==="add"){const name=args[args.indexOf("con-name")+1],type=args[args.indexOf("type")+1]||"ethernet",device=args[args.indexOf("ifname")+1]||name,master=args[args.indexOf("master")+1];connections[name]={type,device,state:"down",master};return `Connection '${name}' successfully added.`;}
    if(action==="modify"){const name=args[2],rawKey=args[3],key=rawKey==="connection.master"?"master":rawKey,value=args.slice(4).join(" ");if(!connections[name])return `Error: unknown connection '${name}'.`;connections[name][key]=value;return "";}
    if(action==="up"||action==="down"){const name=args[2];if(!connections[name])return `Error: unknown connection '${name}'.`;if(action==="up"&&name==="br1"&&connections["bridge-br1"]?.master!=="br1"){connections[name].state="down";serviceLog(state,s.host,"NetworkManager",`activation failed: eno2 profile bridge-br1 is attached to ${connections["bridge-br1"]?.master||"no master"}, expected br1`,"error");return "Error: Connection activation failed: bridge has no compatible slave interfaces.";}connections[name].state=action;if(action==="up"&&name==="br1")connections["bridge-br1"].state="up";const iface=host.interfaces.find(x=>x.name===connections[name].device);if(iface)iface.state=action.toUpperCase();event(state,action==="up"?"info":"warning",`${name} connection ${action} on ${s.host}.`);return `Connection successfully ${action==="up"?"activated":"deactivated"} (${name}).`;}
  }
  return "Error: unsupported nmcli syntax. Try 'nmcli con show'.";
}

function systemInfo(state,s,cmd,args){const host=h(state,s); switch(cmd){case"hostname":return s.host;case"hostnamectl":return `Static hostname: ${s.host}\nOperating System: CentOS Linux 8 (Lab)\nKernel: Linux 4.18.0-477.el8.x86_64\nArchitecture: x86-64`;case"whoami":return s.user;case"id":{const u=args[0]||s.user,rec=host.users[u];return rec?`uid=${rec.uid}(${u}) gid=${rec.uid}(${u}) groups=${rec.uid}(${rec.groups})`:`id: '${u}': no such user`;}case"date":return state.time+" IST";case"uptime":return ` 10:18:42 up ${host.uptime},  2 users,  load average: ${host.load}`;case"free":return "              total        used        free      shared  buff/cache   available\nMem:          15984        5212        7041         412        3731       10120\nSwap:          4095           0        4095";case"df":return `Filesystem                  Size  Used Avail Use% Mounted on\n/dev/mapper/lab-root          80G   ${Math.round(host.disk*.8)}G  ${Math.round(80-host.disk*.8)}G  ${host.disk}% /\n/dev/drbd0                   500G  305G  195G  ${host.disk}% /exports/app`;case"du":return duCommand(host,s,args);case"uname":return "Linux "+s.host+" 4.18.0-477.el8.x86_64 #1 SMP x86_64 GNU/Linux";case"ps":return `USER PID %CPU %MEM VSZ RSS TTY STAT START TIME COMMAND\nroot 1 0.0 0.1 193732 9100 ? Ss Jul29 0:08 /usr/lib/systemd/systemd\nmysql 2210 0.4 8.1 2751032 637120 ? Ssl 10:12 3:42 /usr/sbin/mysqld\nroot 944 0.0 0.1 112932 7252 ? Ss Jul29 0:01 /usr/sbin/sshd -D`;case"top":return `top - 10:18:42 up ${host.uptime}, 2 users, load average: ${host.load}\nTasks: 147 total, 1 running, 146 sleeping\n%Cpu(s): 2.1 us, 0.7 sy, 97.2 id\nMiB Mem : 15984 total, 7041 free`;case"lsblk":return "NAME MAJ:MIN RM SIZE RO TYPE MOUNTPOINT\nsda 8:0 0 100G 0 disk\n├─sda1 8:1 0 1G 0 part /boot\n└─sda2 8:2 0 99G 0 part\n  └─lab-root 253:0 0 80G 0 lvm /\ndrbd0 147:0 0 500G 0 disk /exports/app";case"blkid":return '/dev/sda1: UUID="LAB-BOOT" TYPE="xfs"\n/dev/mapper/lab-root: UUID="LAB-ROOT" TYPE="xfs"';case"mount":return host.mounts.join("\n");case"rpm":return host.packages.join("\n");case"getenforce":return host.selinux||"Enforcing";case"dmesg":return `[    0.000000] Linux version 4.18.0-477.el8.x86_64\n[    2.154201] ${s.host} kernel: lab network interfaces initialized\n[    4.911250] XFS (dm-0): Ending clean mount`;default:return null;}}

export function execute(state,s,raw){ const input=raw.trim(); if(!input)return "";const connectedHost=h(state,s);if(connectedHost&&!connectedHost.online){const disconnected=s.host,previous=s.stack.pop();s.mysql=false;if(previous)Object.assign(s,previous);else Object.assign(s,{host:"bastion01",user:"labadmin",cwd:"/home/labadmin"});return `Connection to ${disconnected} lost: virtual machine is not running.`;} if(s.mysql)return guardedMysqlShell(state,s,input); const safeHistory=input.replace(/(--password(?:=|\s+))\S+/gi,"$1[REDACTED]");s.history.push(safeHistory); h(state,s).history.push(safeHistory);
  const words=shellWords(input),cmd=words[0],args=words.slice(1);
  if(cmd==="clear")return {clear:true}; if(cmd==="help")return help(); if(cmd==="history")return s.history.map((x,i)=>`${String(i+1).padStart(4)}  ${x}`).join("\n");
  if(cmd==="ssh"){const target=args.filter(a=>a!=="-p"&&!/^\d+$/.test(a)).at(-1)||"",[userPart,hostPart]=target.includes("@")?target.split("@"): ["labadmin",target],dest=aliases[hostPart]||hostPart;if(!state.hosts[dest])return `ssh: Could not resolve hostname ${hostPart}: Name or service not known`;if(!state.hosts[dest].online)return `ssh: connect to host ${hostPart} port 22: No route to host`;s.stack.push({host:s.host,user:s.user,cwd:s.cwd});s.host=dest;s.user=userPart;s.cwd=userPart==="root"?"/root":`/home/${userPart}`;return `Last login: Sat Aug  1 10:10:01 2026 from 10.10.0.10\nWelcome to ${dest} — fictional HA lab node.`;}
  if(cmd==="exit"||cmd==="logout"){const prev=s.stack.pop();if(!prev)return "logout";Object.assign(s,prev);return "Connection to lab node closed.";}
  if(cmd==="sudo"){if(args.join(" ")==="su -"||args[0]==="-i"){s.user="root";s.cwd="/root";return "";}return execute(state,s,args.join(" "));} if(cmd==="su"){s.user=args.at(-1)==="-"?"root":args.at(-1)||"root";s.cwd=s.user==="root"?"/root":`/home/${s.user}`;return "";}
  if(cmd==="id"||cmd==="getent"){
    const user=cmd==="getent"?(args.at(-1)||"labadmin"):(args[0]||s.user),host=h(state,s),record=host.users[user];
    if(!record)return cmd==="id"?`id: '${user}': no such user`:"";
    return cmd==="getent"?`${user}:x:${record.uid}:${record.uid}:Lab Administrator:/home/${user}:/bin/bash`:`uid=${record.uid}(${user}) gid=${record.uid}(${user}) groups=${record.uid}(${record.groups})`;
  }
  if(cmd==="setenforce"){h(state,s).selinux=args[0]==="0"||args[0]?.toLowerCase()==="permissive"?"Permissive":"Enforcing";return "";}
  if(cmd==="umount"){const target=args.at(-1);h(state,s).mounts=h(state,s).mounts.filter(m=>!m.includes(` on ${target} `));event(state,"warning",`${target} unmounted on ${s.host}.`);return "";}
  if(cmd==="mount"&&args.length){const target=args.at(-1),source=args.at(-2)||"10.10.30.10:/exports/app";h(state,s).mounts.push(`${source} on ${target} type nfs4 (rw,relatime)`);return "";}
  if(cmd==="kill")return args.at(-1)==="1"?"-bash: kill: (1) - Operation not permitted":`Process ${args.at(-1)} terminated (simulated).`;
  if(cmd==="lsof")return `COMMAND PID USER FD TYPE DEVICE SIZE/OFF NODE NAME\nsshd 944 root 3u IPv4 22101 0t0 TCP *:ssh (LISTEN)`;
  if(cmd==="/usr/libexec/qemu-kvm")return `Supported machines are:\npc-q35-rhel8.6.0  RHEL 8.6.0 PC (Q35 + ICH9, 2009)\npc-i440fx-rhel7.6.0 RHEL 7.6.0 PC (i440FX + PIIX, 1996)\nq35                 Standard PC (Q35 + ICH9, 2009)`;
  const fc=filesCommand(state,s,cmd,args,input);if(fc!==null)return fc; const si=systemInfo(state,s,cmd,args);if(si!==null)return si;
  if(cmd==="systemctl")return serviceCommand(state,s,args);
  if(cmd==="pcs")return pcsCommand(state,s,args);if(cmd==="crm")return pcsStatus(state,s);if(cmd.startsWith("corosync-"))return cmd.includes("quorum")?"Quorum information\n------------------\nNodes: 2\nQuorate: Yes\nVotequorum information\nExpected votes: 2\nTotal votes: 2":"Printing ring status.\nLocal node ID 1\nRING ID 0\n  status = ring 0 active with no faults";if(cmd==="drbdadm"||cmd==="drbdsetup"){const entry=clusterForHost(state,s.host);if(cmd==="drbdadm"&&entry){const cluster=entry[1],action=args.find(arg=>["connect","disconnect","secondary","primary"].includes(arg));if(action==="secondary"&&cluster.roles==="Primary/Primary"){cluster.roles=s.host===cluster.nodes[0]?"Secondary/Primary":"Primary/Secondary";cluster.splitBrainStage=1;serviceLog(state,s.host,"drbd","local resource demoted to Secondary for split-brain recovery","warning");return "";}if(action==="disconnect"&&cluster.splitBrainStage===1){cluster.drbd="StandAlone";cluster.splitBrainStage=2;return "";}if(action==="connect"){if(cluster.roles==="Primary/Primary"||cluster.splitBrainStage){if(args.includes("--discard-my-data")&&cluster.splitBrainStage===2){cluster.drbd="Connected";cluster.roles="Secondary/Primary";cluster.splitBrainStage=3;cluster.nodes.forEach(n=>serviceLog(state,n,"drbd",`${entry[0]} split-brain recovery completed; discarded divergent data on selected Secondary`,"notice"));event(state,"info",`${entry[0]} DRBD split-brain recovered.`);return "";}serviceLog(state,s.host,"drbd","connection refused: split-brain requires explicit victim demotion and --discard-my-data recovery","alert");return "Command 'drbdsetup connect r0' terminated with exit code 17: State change failed: (-17) Need access to UpToDate data";}if(cluster.drbdPortBlocked){serviceLog(state,s.host,"drbd","connect failed: peer 10.10.20.22:7789 Connection refused; check firewalld","error");return "r0: Failure: (162) Invalid configuration request: peer connection to 10.10.20.22:7789 refused";}cluster.drbd="Connected";cluster.roles="Primary/Secondary";cluster.nodes.forEach(n=>serviceLog(state,n,"drbd",`${entry[0]} peer connection established; disks UpToDate`,"notice"));event(state,"info",`${entry[0]} DRBD peers reconnected.`);return "";}}return drbdOutput(state,s);}
  if(cmd==="mysql"){
    if(!isActive(h(state,s).services.mariadb)&&s.host.includes("mysql"))return "ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock'";
    const restoreAt=words.indexOf("<");if(restoreAt>=0){const file=resolvePath(s,words[restoreAt+1]);if(h(state,s).files[file]===undefined)return `-bash: ${words[restoreAt+1]}: No such file or directory`;event(state,"info",`Logical backup ${words[restoreAt+1]} restored into ${args[0]} on ${s.host}.`);return "";}
    const inline=input.match(/-e\s+["'](.+)["']/);if(inline)return guardedMysqlShell(state,s,inline[1]);s.mysql=true;return "Welcome to the MariaDB monitor. Commands end with ; or \\g.\nServer version: 10.5.22-MariaDB-log HA Infrastructure Lab\n\nType 'help;' for help. Type 'exit;' to quit.";
  }
  if(cmd==="mysqldump"){const redir=words.indexOf(">");const file=redir>=0?words[redir+1]:"backup.sql";h(state,s).files[resolvePath(s,file)]="-- HA Lab logical backup\nCREATE TABLE users (id INT PRIMARY KEY, name VARCHAR(80));\nINSERT INTO users VALUES (1,'Fictional User');\n";event(state,"info",`Logical MySQL backup ${file} created on ${s.host}.`);return "";}
  const pc=platformCommand(state,s,cmd,args,input);if(pc!==null)return pc;const nc=networking(state,s,cmd,args,input);if(nc!==null)return nc;
  if(cmd==="pure-pw")return "labftp          /srv/ftp/labftp/./\nmediaftp        /srv/ftp/mediaftp/./";
  if(cmd==="wget"){const name=basename(args.at(-1));h(state,s).files[resolvePath(s,name)]=`[simulated downloaded artifact: ${name}]`;return `Saving to: '${name}'\n100%[==================>] 1,024  --.-KB/s (simulated; no network used)`;}
  if(cmd==="journalctl"){const host=h(state,s),unitAt=args.indexOf("-u"),unit=unitAt>=0?args[unitAt+1]?.replace(".service",""):null,specific=unit?host.files[logPathFor(s.host,unit)]||"":"";return `${host.files["/var/log/messages"]||""}${specific}${specific?"":"-- No entries for requested unit --\n"}Aug 02 09:18:59 ${s.host} systemd-journald[611]: Journal query completed.`;}if(cmd==="yum"){if(args[0]==="install"){const pkg=args.find(a=>!a.startsWith("-")&&a!=="install"),available={telnet:"0.17-76.el8","nmap-ncat":"2:7.70-11.el8",traceroute:"3:2.1.0-6.el8","bind-utils":"32:9.11.36-16.el8",rsync:"3.1.3-19.el8",lsof:"4.93.2-1.el8"};if(!pkg||!available[pkg])return `Last metadata expiration check: 0:03:12 ago.\nNo match for argument: ${pkg||""}\nError: Unable to find a match: ${pkg||""}`;const host=h(state,s),record=`${pkg}-${available[pkg]}.x86_64`;host.packages=host.packages.filter(installed=>!installed.startsWith("telent-"));if(host.packages.some(installed=>installed.startsWith(`${pkg}-`)))return `Package ${record} is already installed.\nDependencies resolved.\nNothing to do.\nComplete!`;host.packages.push(record);return `Installed:\n  ${pkg}.x86_64 ${available[pkg]}\nComplete!`;}if(args[0]==="update"){event(state,"info",`Simulated package update completed on ${s.host}.`);return "Dependencies resolved.\nNothing to do.\nComplete!";}return h(state,s).packages.join("\n");}
  if(cmd==="nmcli")return nmcliCommand(state,s,args);if(cmd==="bridge")return Object.values(h(state,s).connections).filter(x=>x.master).map((x,i)=>`${i+2}: ${x.device} state ${x.state.toUpperCase()} : <BROADCAST,MULTICAST,${x.state.toUpperCase()}> master ${x.master}`).join("\n")||"No bridge slave interfaces.";if(cmd==="virsh"){
    if(!s.host.includes("kvm"))return "error: failed to connect to the hypervisor\nerror: no connection driver available for qemu:///system";
    const domains=Object.entries(state.vms||{}).filter(([,vm])=>vm.hypervisor===s.host),action=args[0]||"list",runningDomains=domains.filter(([,vm])=>state.hosts[vm.guest].online);
    if(action==="list"){
      const includeStopped=args.includes("--all"),rows=domains.filter(([,vm])=>includeStopped||state.hosts[vm.guest].online).map(([name,vm],index)=>`${state.hosts[vm.guest].online?String(index+1).padStart(2):" -"}    ${name.padEnd(14)} ${state.hosts[vm.guest].online?"running":"shut off"}`);
      return ` Id   Name           State\n---------------------------------\n${rows.join("\n")}`;
    }
    const target=args[1],byId=/^\d+$/.test(target||"")?runningDomains[Number(target)-1]:null,name=byId?.[0]||target,vm=byId?.[1]||state.vms?.[name];
    if(!vm||vm.hypervisor!==s.host)return `error: failed to get domain '${target}'`;
    if(action==="console"){
      if(!state.hosts[vm.guest].online)return `error: Failed to start console: Guest is not running`;
      s.stack.push({host:s.host,user:s.user,cwd:s.cwd});s.host=vm.guest;s.user="root";s.cwd="/root";
      return `Connected to domain '${name}'\nEscape character is ^]`;
    }
    if(["start","shutdown","reboot"].includes(action)){const result=setHostPower(state,vm.guest,action);if(result.startsWith("Error:")||result.includes("already running")||result.includes("not running"))return `error: ${result}`;return action==="start"?`Domain '${name}' started`:action==="shutdown"?`Domain '${name}' is being shutdown`:`Domain '${name}' is being rebooted`;}
    if(action==="dominfo")return `Id: ${state.hosts[vm.guest].online?runningDomains.findIndex(([domain])=>domain===name)+1:"-"}\nName: ${name}\nUUID: 00000000-0000-0000-0000-${String(domains.findIndex(([domain])=>domain===name)+1).padStart(12,"0")}\nOS Type: hvm\nState: ${state.hosts[vm.guest].online?"running":"shut off"}\nCPU(s): ${vm.vcpus}\nMax memory: ${vm.memoryMiB*1024} KiB\nAutostart: enable`;
    return `error: unsupported virsh command '${action}'`;
  }
  if(cmd==="reboot"||cmd==="shutdown"){const hostname=s.host;setHostPower(state,hostname,cmd);const previous=s.stack.pop();if(previous)Object.assign(s,previous);return `Connection to ${hostname} closed by remote host.`;}
  if(cmd==="scp"||cmd==="rsync")return `sent 1,248 bytes  received 42 bytes  2,580.00 bytes/sec\ntotal size is 1,024  speedup is 0.79 (simulated)`;
  return `-bash: ${cmd}: command not found\nLab hint: type 'help' to list the commands available in this simulator.`;
}

export function injectScenario(state,id){
 const set=(host,service,status="inactive (dead)")=>state.hosts[host].services[service]=status;
 switch(Number(id)){
  case 1:set("haproxy01","haproxy");state.hosts.haproxy01.files["/run/haproxy.pid"]="2188\n";serviceLog(state,"haproxy01","haproxy","worker 2188 terminated by SIGSEGV; stale pidfile /run/haproxy.pid was not removed","critical");failover(state,"haproxy","haproxy01");break;
  case 2:state.hosts.haproxy01.files["/etc/haproxy/haproxy.cfg"]+="\nINVALID broken_directive\n";set("haproxy01","haproxy");serviceLog(state,"haproxy01","haproxy","parsing [/etc/haproxy/haproxy.cfg:16]: unknown keyword 'INVALID'; fatal configuration errors","alert");break;
  case 3:set("mysql-core01","mariadb");serviceLog(state,"mysql-core01","mariadb","InnoDB: fatal simulated storage error; mariadbd process exited status=1","critical");failover(state,"database","mysql-core01");state.clusters.database.failures=1;state.clusters.database.lastFailedNode="mysql-core01";serviceLog(state,"mysql-core02","mariadb","promoted local database instance for clustered write service","notice");break;
  case 4:state.mysql.io=false;state.mysql.sql=false;state.mysql.skipCounterReady=false;state.mysql.error="Error 1062: Duplicate entry '8421' for key 'PRIMARY'";serviceLog(state,"mysql-slave01","mariadb","Replica SQL thread stopped: Error 1062 Duplicate entry '8421' for key 'PRIMARY'","error");break;
  case 5:state.clusters.database.drbd="Disconnected";state.clusters.database.drbdPortBlocked=true;serviceLog(state,"mysql-core01","drbd","r0: peer connection lost; connect to 10.10.20.22:7789 failed: Connection refused","warning");serviceLog(state,"mysql-core01","firewalld","rich rule reload omitted DRBD port 7789/tcp","error");serviceLog(state,"mysql-core02","drbd","r0: peer unreachable; replication state Disconnected","warning");break;
  case 6:state.clusters.database.drbd="StandAlone";state.clusters.database.roles="Primary/Primary";state.clusters.database.splitBrainStage=0;serviceLog(state,"mysql-core01","drbd","Split-Brain detected, dropping connection; local and peer roles Primary/Primary","alert");serviceLog(state,"mysql-core02","drbd","Split-Brain detected, manual victim selection and resynchronization required","alert");break;
  case 7:{const old=state.clusters.database.owner;failover(state,"database",old);state.clusters.database.failures=1;state.clusters.database.lastFailedNode=old;serviceLog(state,old,"pacemaker","database VIP monitor failed during planned migration; failure count retained","warning");break;}
  case 8:state.hosts.san01.disk=98;state.hosts.san01.files["/tmp/core.22011"]="[56 GiB simulated core image]";serviceLog(state,"san01","nfs-server","filesystem /exports/app usage critical at 98%; writes may fail with ENOSPC","critical");appendLog(state,"san01","/var/log/messages","Aug 02 09:18:42 san01 kernel: XFS warning: low free space on /dev/drbd0; 56G core file detected in /tmp");break;
  case 9:state.hosts.san01.online=false;Object.keys(state.hosts.san01.services).forEach(service=>state.hosts.san01.services[service]="inactive (dead)");serviceLog(state,"san01","nfs-server","NFS server became unresponsive; cluster monitor timeout","critical");failover(state,"storage","san01");state.hosts.san02.services["nfs-server"]="active (running)";serviceLog(state,"san02","nfs-server","exportfs completed; NFS service active after VIP migration","notice");break;
  case 10:set("ftp01","pure-ftpd");state.hosts.ftp01.files["/etc/pki/tls/certs/lab-ftp.pem"]="LAB FTP CERTIFICATE serial=2025-01 expires=2026-07-31\n";state.ftp={tlsValid:false,passiveOpen:false,reloaded:false};serviceLog(state,"ftp01","pure-ftpd","TLS handshake failed: certificate expired Jul 31 2026; passive range 30000-31000 rejected by firewalld","error");break;
  case 13:state.hosts.kvm01.connections.br1.state="down";state.hosts.kvm01.connections["bridge-br1"].state="down";state.hosts.kvm01.connections["bridge-br1"].master="br0";serviceLog(state,"kvm01","NetworkManager","bridge br1 activation failed: eno2 profile is enslaved to br0 instead of br1","error");appendLog(state,"kvm01","/var/log/libvirt/libvirtd.log","2026-08-02 09:18:42.112+0000: error : qemuDomainInterfaceStartDevice: network bridge br1 has no usable slave");break;
  case 14:set("rabbitmq01","rabbitmq-server");state.hosts.rabbitmq01.files["/var/lib/rabbitmq/.erlang.cookie"]="WRONG-NODE-COOKIE\n";state.rabbitOnline=2;serviceLog(state,"rabbitmq01","rabbitmq-server","BOOT FAILED: invalid challenge reply from rabbit@rabbitmq02; Erlang cookie mismatch","error");serviceLog(state,"rabbitmq02","rabbitmq-server","rabbit@rabbitmq01 rejected during distribution handshake; quorum retained with 2 nodes","warning");break;
  case 15:set("cassandra01","cassandra");state.hosts.cassandra01.files["/etc/cassandra/cassandra.yaml"]=state.hosts.cassandra01.files["/etc/cassandra/cassandra.yaml"].replace("listen_address: 10.10.61.21","listen_address: 127.0.0.1");state.cassandraOnline=2;serviceLog(state,"cassandra01","cassandra","ConfigurationException: listen_address 127.0.0.1 is not reachable by peers","error");serviceLog(state,"cassandra02","cassandra","InetAddress /10.10.61.21 is now DOWN","warning");break;
  case 16:state.elastic="red";state.elasticAllocation="none";serviceLog(state,"elasticsearch01","elasticsearch","persistent setting cluster.routing.allocation.enable changed to none by maintenance automation","warning");serviceLog(state,"elasticsearch02","elasticsearch","cluster health status changed from YELLOW to RED; primary shards unassigned because allocation is disabled","error");break;
  case 18:Object.values(state.hosts).filter(x=>x.dc==="primary"&&x.hostname!=="bastion01").forEach(x=>{serviceLog(state,x.hostname,"systemd","site heartbeat lost during simulated primary data-centre outage","critical");x.online=false;});state.dnsTarget="recovery-pending";appendLog(state,"dns01","/var/log/messages","Aug 02 09:18:42 dns01 named[2010]: CRITICAL primary site health checks failed; recovery target pending promotion");break;
  case 19:state.activeDc="recovery";state.dnsTarget="recovery";state.clusters.database.owner="dr-mysql-core01";state.mysql.primary="dr-mysql-core01";serviceLog(state,"dr-haproxy01","pacemaker","recovery HAProxy VIP promoted and health-routing target enabled","notice");serviceLog(state,"dr-mysql-core01","mariadb","recovery database promoted to writable primary after synchronization check","notice");serviceLog(state,"dr-san01","nfs-server","recovery exports promoted read-write","notice");break;
  case 20:Object.values(state.hosts).filter(x=>x.dc==="primary").forEach(x=>x.online=true);state.activeDc="primary";state.dnsTarget="primary";state.clusters.database.owner="mysql-core01";state.mysql.primary="mysql-core01";serviceLog(state,"haproxy01","pacemaker","controlled failback completed; primary request path restored","notice");serviceLog(state,"mysql-core01","mariadb","write service returned after GTID synchronization validation","notice");serviceLog(state,"san01","nfs-server","primary storage export restored after rsync verification","notice");break;
 }
 state.scenarios[id]={active:true,status:"in_progress",started:new Date().toISOString(),lastCheck:""};event(state,"critical",`Exercise ${id} injected into the lab.`);
}
