const definitions = [
  [1,"Public ingress node unavailable","Traffic is being served by the standby load balancer; one HAProxy node remains unavailable.",["haproxy01","haproxy02"],["pcs status","journalctl -u haproxy","ls -l /run/haproxy.pid","ps aux"],"The VIP is healthy and both HAProxy nodes are ready."],
  [2,"HAProxy fails to start","The active edge node cannot start HAProxy following a recent configuration change.",["haproxy01"],["haproxy -c -f /etc/haproxy/haproxy.cfg","tail /var/log/messages"],"Configuration validates and HAProxy runs."],
  [3,"Database write service failed over","The database VIP moved to the peer and Pacemaker reports a failed resource action.",["mysql-core01","mysql-core02"],["pcs status","journalctl -u mariadb","tail /var/log/pacemaker/pacemaker.log","mysql -e 'SELECT @@hostname;'"],"The survivor owns the VIP and Pacemaker has no failed actions."],
  [4,"MySQL replication stopped","The read replica is no longer applying transactions from the active database.",["mysql-core01","mysql-slave01","dr-mysql-core01"],["mysql","SHOW REPLICA STATUS\\G","tail /var/log/mariadb/mariadb.log"],"Both replication threads run with zero lag and no Last_Error."],
  [5,"DRBD peer disconnected","Database block replication between the two core nodes is Disconnected.",["mysql-core01","mysql-core02"],["drbdadm status","journalctl -u drbd","firewall-cmd --list-all","ss -lntp"],"DRBD peers are Connected and UpToDate over port 7789."],
  [6,"DRBD reports Primary/Primary","The database replication resource is StandAlone and both peers report the Primary role.",["mysql-core01","mysql-core02"],["drbdsetup status","grep -i split-brain /var/log/drbd.log","corosync-quorumtool"],"One Primary remains; the selected Secondary has resynchronized."],
  [7,"Database VIP moved with failed action","The write VIP is online on the peer, but Pacemaker still reports a failed monitor action.",["mysql-core01","mysql-core02"],["pcs status","tail /var/log/pacemaker/pacemaker.log","ip a","mysql -e 'SELECT @@hostname;'"],"VIP ownership and DRBD role agree with no failed actions."],
  [8,"SAN filesystem utilization critical","Monitoring reports 98% utilization on the active storage node and application writes are at risk.",["san01"],["df -h","du -sh /tmp/*","find /tmp -maxdepth 1 -name 'core.*'"],"Filesystem use is below 80% and application writes are safe."],
  [9,"Active SAN node offline","SAN01 is unreachable and the NFS storage VIP has migrated to SAN02.",["san01","san02","web01"],["pcs status","showmount -e san-vip","pcs cluster start san01","mount"],"Both SAN nodes are online and clients can use the healthy NFS VIP."],
  [10,"Secure FTP transfers failing","TLS logins and passive data transfers are failing on the primary FTP node.",["ftp01"],["systemctl status pure-ftpd","tail /var/log/pureftpd.log","firewall-cmd --list-all","ss -lntp"],"Secure FTP logins and passive transfers succeed."],
  [13,"Virtual machines lost backend connectivity","Guests attached to the private bridge cannot reach backend services.",["kvm01"],["nmcli conn show","bridge link show","journalctl -u NetworkManager","ip route"],"Private-bridge guest connectivity is restored."],
  [14,"RabbitMQ cluster running with two nodes","RabbitMQ reports only two of three expected members in the running-node list.",["rabbitmq01","rabbitmq02","rabbitmq03"],["rabbitmqctl cluster_status","journalctl -u rabbitmq-server","tail /var/log/rabbitmq/rabbit@rabbitmq01.log"],"All three RabbitMQ nodes run without partitions."],
  [15,"Cassandra node marked DOWN","Gossip reports one primary-site Cassandra node as unavailable.",["cassandra01","cassandra02","cassandra03"],["nodetool status","journalctl -u cassandra","grep listen_address /etc/cassandra/cassandra.yaml"],"All Cassandra nodes report UN."],
  [16,"Elasticsearch cluster RED","Three primary shards are unassigned while all Elasticsearch processes remain online.",["elasticsearch01","elasticsearch02","elasticsearch03"],["curl -s localhost:9200/_cluster/health?pretty","curl -s localhost:9200/_cluster/settings?pretty","curl -s localhost:9200/_cluster/allocation/explain?pretty"],"Cluster health is green with zero unassigned shards."],
  [18,"Primary data centre unreachable","Health checks cannot reach any service nodes in the primary site.",["dns01","haproxy01","mysql-core01","san01"],["dig app.lab.internal","pcs status"],"Primary is isolated and recovery readiness is confirmed."],
  [19,"Recovery site promotion required","The primary request path is unavailable and synchronized recovery services are on standby.",["dr-haproxy01","dr-mysql-core01","dr-san01"],["pcs status","drbdadm status","mysql -e 'SHOW REPLICA STATUS\\G'"],"Recovery DC is active and receives the request path."],
  [20,"Primary site ready for controlled return","Primary services are online and synchronized while traffic is still served by recovery.",["haproxy01","mysql-core01","san01"],["pcs status","drbdadm status","dig app.lab.internal"],"Primary serves traffic again with replication healthy."],
];

const rootCauses={1:"HAProxy crashed and left /run/haproxy.pid behind, so systemd refuses a clean start.",2:"An invalid directive was added to haproxy.cfg.",3:"The active MariaDB process crashed; Pacemaker failed over correctly but retained a failed monitor action.",4:"A duplicate primary key stopped only the replica SQL thread.",5:"A firewalld regression removed TCP 7789, so DRBD cannot reach its peer.",6:"Both DRBD peers were promoted, producing divergent Primary data.",7:"The VIP moved successfully, but a failed monitor record remains and must be cleared.",8:"A 56 GiB application core file filled the SAN filesystem.",9:"SAN01 lost power; fencing and storage failover moved NFS to SAN02.",10:"The FTP certificate expired and the passive port range is absent from firewalld.",13:"The eno2 connection profile was accidentally assigned to br0 instead of br1.",14:"RabbitMQ01 has a different Erlang cookie and is rejected during the distribution handshake.",15:"Cassandra01 is configured with loopback as its listen_address.",16:"A persistent cluster setting disabled all shard allocation.",18:"The primary site lost all service-node heartbeats.",19:"The recovery site is healthy but not yet the authoritative request path.",20:"Primary services have returned and require controlled routing restoration."};
const repairs={1:"Remove the stale PID only after confirming no HAProxy process owns it, then start HAProxy and recheck the VIP.",2:"Remove the invalid directive, validate the configuration, then restart.",3:"Verify the survivor owns the write VIP, then clean up database-group failure history.",4:"Validate the 1062 conflict, skip the single known transaction, start replication, and verify Last_Error is empty.",5:"Restore 7789/tcp permanently, reload firewalld, then reconnect DRBD.",6:"Demote the chosen victim, disconnect it, then reconnect with --discard-my-data so it resynchronizes from the authoritative Primary.",7:"Verify the current writer and VIP, then clean up database-group.",8:"Identify and remove the simulated core file, then verify capacity.",9:"Power on or rejoin SAN01 while keeping the healthy VIP on SAN02.",10:"Install the renewed certificate, permanently allow only 30000-31000/tcp, reload firewalld, and start Pure-FTPd.",13:"Set bridge-br1 connection.master to br1 and reactivate br1.",14:"Replace RabbitMQ01's cookie with the cluster copy and start the node.",15:"Correct listen_address to 10.10.61.21, start Cassandra, and verify gossip.",16:"Set cluster.routing.allocation.enable to all and verify the primary shards allocate.",18:"Confirm total primary loss and recovery readiness.",19:"Promote synchronized recovery services and switch DNS.",20:"Verify synchronization, restore primary ownership, and switch DNS back."};

export const scenarios = definitions.map(([id,title,objective,affected,commands,success])=>({id,title,objective,affected,commands,success,symptoms:objective,hint:`Start on ${affected[0]}. Read the service or cluster logs, identify the persistent cause, and prove a restart alone does not hide it.`,explanation:`Root cause: ${rootCauses[id]}\n\nExpected recovery: ${repairs[id]}\n\nValidate from the service path after the repair; a running process alone is not sufficient.`}));

const activeService=(state,host,service)=>state.hosts[host]?.online&&state.hosts[host]?.services[service]?.startsWith("active");
const noCoreFiles=host=>!Object.keys(host.files).some(path=>path.startsWith("/tmp/core."));
const evidenceCommands={
  1:["pcs","systemctl","journalctl","ls","ps","rm"],2:["haproxy","tail","sed","vi","vim","nano","systemctl"],3:["pcs","systemctl","journalctl","tail","mysql"],4:["mysql","tail"],5:["drbdadm","drbdsetup","cat","pcs","journalctl","firewall-cmd","ss"],6:["drbdadm","drbdsetup","grep","corosync-quorumtool","journalctl"],7:["pcs","tail","ip","mysql"],8:["df","du","find","rm"],9:["pcs","showmount","mount","powerctl"],10:["systemctl","tail","firewall-cmd","ss","cp"],13:["nmcli","bridge","journalctl","ip"],14:["rabbitmqctl","systemctl","journalctl","tail","cp"],15:["nodetool","systemctl","journalctl","grep","sed","vi","vim","nano"],16:["curl"],18:["dig","pcs"],19:["pcs","drbdadm","mysql"],20:["pcs","drbdadm","dig"]
};
const hasScenarioEvidence=(state,id)=>{const allowed=evidenceCommands[id]||[];return Object.values(state.hosts).flatMap(host=>host.history||[]).some(line=>allowed.some(command=>line===command||line.startsWith(`${command} `)));};
const scenarioHealthy={
  1:state=>Boolean(state.clusters.haproxy.owner)&&activeService(state,"haproxy01","haproxy")&&activeService(state,"haproxy02","haproxy")&&state.hosts.haproxy01.files["/run/haproxy.pid"]===undefined,
  2:state=>activeService(state,"haproxy01","haproxy")&&!state.hosts.haproxy01.files["/etc/haproxy/haproxy.cfg"].includes("INVALID"),
  3:state=>Boolean(state.clusters.database.owner&&activeService(state,state.clusters.database.owner,"mariadb"))&&!state.clusters.database.failures,
  4:state=>state.mysql.io&&state.mysql.sql&&!state.mysql.error&&state.mysql.lag===0,
  5:state=>state.clusters.database.drbd==="Connected"&&!state.clusters.database.drbdPortBlocked,
  6:state=>state.clusters.database.drbd==="Connected"&&state.clusters.database.roles!=="Primary/Primary"&&state.clusters.database.splitBrainStage===3,
  7:state=>Boolean(state.clusters.database.owner&&state.hosts[state.clusters.database.owner]?.online)&&!state.clusters.database.failures,
  8:state=>state.hosts.san01.disk<80&&noCoreFiles(state.hosts.san01),
  9:state=>state.hosts.san01.online&&state.hosts.san02.online&&state.clusters.storage.owner==="san02"&&activeService(state,"san02","nfs-server")&&state.clusters.storage.drbd==="Connected",
  10:state=>activeService(state,"ftp01","pure-ftpd")&&state.ftp.tlsValid&&state.ftp.passiveOpen&&state.hosts.ftp01.files["/etc/pki/tls/certs/lab-ftp.pem"]===state.hosts.ftp01.files["/etc/pki/tls/certs/lab-ftp-renewed.pem"],
  13:state=>state.hosts.kvm01.connections.br1?.state==="up"&&state.hosts.kvm01.connections["bridge-br1"]?.state==="up"&&state.hosts.kvm01.connections["bridge-br1"]?.master==="br1",
  14:state=>state.rabbitOnline===3&&state.hosts.rabbitmq01.files["/var/lib/rabbitmq/.erlang.cookie"]===state.hosts.rabbitmq01.files["/etc/rabbitmq/lab.erlang.cookie"]&&[1,2,3].every(n=>activeService(state,`rabbitmq0${n}`,"rabbitmq-server")),
  15:state=>state.cassandraOnline===3&&state.hosts.cassandra01.files["/etc/cassandra/cassandra.yaml"].includes("listen_address: 10.10.61.21")&&[1,2,3].every(n=>activeService(state,`cassandra0${n}`,"cassandra")),
  16:state=>state.elastic==="green"&&state.elasticAllocation==="all"&&[1,2,3].every(n=>activeService(state,`elasticsearch0${n}`,"elasticsearch")),
  18:state=>state.dnsTarget==="recovery-pending"&&Object.values(state.hosts).filter(h=>h.dc==="primary"&&h.hostname!=="bastion01").every(h=>!h.online),
  19:state=>state.activeDc==="recovery"&&state.dnsTarget==="recovery"&&state.mysql.primary==="dr-mysql-core01",
  20:state=>state.activeDc==="primary"&&state.dnsTarget==="primary"&&state.mysql.primary==="mysql-core01"
};

export function assessScenario(state,id){
  const run=state.scenarios?.[id];
  if(!run)return {passed:false,healthy:false,observed:false,message:"Start the exercise before checking it."};
  const observed=hasScenarioEvidence(state,id),healthy=Boolean(scenarioHealthy[id]?.(state));
  if(!observed)return {passed:false,healthy,message:"Run a relevant diagnostic or repair command for this exercise, then check again."};
  if(!healthy)return {passed:false,healthy,observed,message:"The fault is still present. Continue diagnosis and repair, then check again."};
  return {passed:true,healthy,observed,message:"Success conditions verified. Exercise completed."};
}
